import { StyleSheet, Dimensions } from "react-native";
import Colors from "./Colors";

const windowHeight = Dimensions.get("window").height;
const windowWidth = Dimensions.get("window").width;
const tabHeight = 50;
const galleryGridWidth = Math.floor((windowWidth - 20) / 4);
const galleryGridHeight = Math.floor((windowWidth - 20) / 4);

const styles = StyleSheet.create({
  mainContainer: {
    width: windowWidth,
    height: windowHeight,
    backgroundColor: "white",
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },
  Label: {
    marginTop: 20,
    fontSize: 5,
    fontWeight: "200",
  },
  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: 12,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor : Colors.white
  },
  body: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    // paddingHorizontal: 20,
    // paddingVertical: 20,
    paddingVertical: 5,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
  flatListBox: {
    marginTop: 15,
    flex: 1,
    bottom: "1.5%",
    height: "100%",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "white",
  },
  imageBox: {
    padding: 10,
    flex: 1,
    flexDirection: "column",
  },
  // image: {
  //   borderWidth: 1,
  //   borderColor: "#D3D3D3",
  //   borderRadius: 15,
  // },
  imageName: {  
    backgroundColor : 'rgba(255,255,255, 0.6)',
    position : 'absolute',
    bottom : 10 ,
    left : 10 ,
    padding : 8,
    borderRadius: 10,
    margin : 10,    // width : '100%',
    color: "black",
    // bottom: "150%",
    fontSize: 18,
    fontWeight: "600",
  },
  blankBoxName: {
    color: "grey",
    bottom: "260%",
    left: "19%",
    fontSize: 19,
    fontWeight: "700",
  },
  formControlLabel: {
    // top: "3%",
    marginTop: 20,
    // fontSize: 15,
    // fontWeight: '200'
  },
  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderBottomWidth: 0.5,
    borderColor: "grey",
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: Colors.lableSize,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  flex1: { flex: 1 },
  width100: { width: "100%" },
  width85: { width: "85%" },
  width20: { width: "20%" },
  width75: { width: "75%" },
  w100: { width: 100 },
  mt60: { marginTop: 60 },
  mb50: { marginBottom: 50 },
  mb10: { marginBottom: 10 },
  mb0: { marginBottom: 0 },
  ml10: { marginLeft: 10 },
  mr10: { marginRight: 10 },
  mt10: { marginTop: 10 },
  mt5: { marginTop: 5 },
  h50: { height: 50 },
  mh4: { marginHorizontal: 4 },
  p0: { padding: 0 },
  p3: { padding: 3 },
  p5: { padding: 5 },
  p10: { padding: 10 },
  pr5: { paddingRight: 5 },
  pl5: { paddingLeft: 5 },
  pv5: { paddingVertical: 5 },
  h10: { height: 10 },
  heightAuto: { height: "auto" },
  safeAreaViewStyle: { flex: 1, backgroundColor: "transparent" },
  sectionHeaderText: { fontSize: 16, color: Colors.white },
  sectionHeaderTextUser: { fontSize: 16, color: Colors.primary },
  BGWhite: { backgroundColor: Colors.white },
  alignItemsCenter: { alignItems: "center" },
  flexDirectionRow: { display: "flex", flexDirection: "row" },
  justifyContentBetween: { justifyContent: "space-between" },
  justifyContentCenter: { justifyContent: "center" },
  justifyContentAround: { justifyContent: "space-around" },
  textAlignCenter: { textAlign: "center" },
  fontWeightNormal: { fontWeight: "normal" },
  qrDownloadImage: { height: 200, width: 200 },
  downloadFileButtonText: { fontSize: 16, marginHorizontal: 5 },
  listEmptyComponentStyle: {
    color: Colors.textColor,
    textAlign: "center",
    marginTop: 10,
  },
  animalCodeTextInput: { width: "100%", textAlign: "left", fontSize: 14 },
  imageContainer: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 3,
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  inputContainer: {
    padding: "1%",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },
  Label: {
    marginTop: 20,
    fontSize: 5,
    fontWeight: "200",
  },
  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: 12,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
  },
  body: {
    // flex: 1,
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    paddingVertical: 20,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
	mainContainer: {
		width: windowWidth,
		height: windowHeight,
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
    mainContainer: {
        backgroundColor: "white",
        flex: 1,
        alignItems: "center",
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "grey"
    },
    formContainer: {
        width: "100%",
        height: "100%",
        paddingHorizontal: 20,
        paddingVertical: 20,
        backgroundColor: "white"
    },
    formViews: {
        width: "100%",
        // height: "80%",
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: "white"
    },
    Label: {
        marginTop: 20,
        fontSize: 5,
        fontWeight: '200'
    },
    inputFlieds: {
        // borderBottomWidth: 1,
        // borderColor: "grey",
        fontSize: 12,
        color: "black",
        borderColor: "#00008B",
    },
    feetBox: {
        padding: "1%",
        left: "55%",
        bottom: "10.5%",
        width: "45%"
    },
    container: {
        flex: 1,
        alignItems: "center",
        marginTop: 15,
    },
    body: {
        width: "100%",
        height: "100%",
        marginTop : 500 ,
        paddingHorizontal:10,
        // paddingHorizontal: 20,
        // paddingVertical: 20,
        paddingVertical:5,
        backgroundColor: "white"
    },

    TextInputContainer: {
        marginVertical: 20
    },
    nextBtn: {
        marginVertical: 12,
        backgroundColor: "#7CC0CF",
        width: "40%",
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        marginLeft: "auto",
        marginRight: "auto",
        borderRadius: 10,
    },
    btnText: {
        color: "white"
    },
    formControlLabel: {
        // top: "3%",
        marginTop: 20,
        // fontSize: 15,
        // fontWeight: '200'
    },
    fieldBox: {
        alignItems: "center",
        width: "100%",
        overflow: "hidden",
        flexDirection: "row",
        padding: 5,
        borderRadius: 3,
        borderBottomWidth: 0.5,
        borderColor: "grey",
        backgroundColor: "#fff",
        height: "auto",
        justifyContent: "space-between",
    },
    labelName: {
        color: Colors.labelColor,
        // lineHeight: 40,
        fontSize: Colors.lableSize,
        paddingLeft: 4,
        height: "auto",
        paddingVertical: 10,
    },
    flex1: { flex: 1 },
    width100: { width: "100%" },
    width85: { width: "85%" },
    width20: { width: "20%" },
    width75: { width: "75%" },
    w100: { width: 100 },
    mt60: { marginTop: 60 },
    mb50: { marginBottom: 50 },
    mb10: { marginBottom: 10 },
    mb0: { marginBottom: 0 },
    ml10: { marginLeft: 10 },
    mr10: { marginRight: 10 },
    mt10: { marginTop: 10 },
    mt5: { marginTop: 5 },
    h50: { height: 50 },
    mh4: { marginHorizontal: 4 },
    p0: { padding: 0 },
    p3: { padding: 3 },
    p5: { padding: 5 },
    p10: { padding: 10 },
    pr5: { paddingRight: 5 },
    pl5: { paddingLeft: 5 },
    pv5: { paddingVertical: 5 },
    h10: { height: 10 },
    heightAuto: { height: "auto" },
    safeAreaViewStyle: { flex: 1, backgroundColor: "transparent" },
    sectionHeaderText: { fontSize: 16, color: Colors.white },
    sectionHeaderTextUser: { fontSize: 16, color: Colors.primary },
    BGWhite: { backgroundColor: Colors.white },
    alignItemsCenter: { alignItems: "center" },
    flexDirectionRow: { display: "flex", flexDirection: "row" },
    justifyContentBetween: { justifyContent: "space-between" },
    justifyContentCenter: { justifyContent: "center" },
    justifyContentAround: { justifyContent: "space-around" },
    textAlignCenter: { textAlign: "center" },
    fontWeightNormal: { fontWeight: "normal" },
    qrDownloadImage: { height: 200, width: 200 },
    downloadFileButtonText: { fontSize: 16, marginHorizontal: 5 },
    listEmptyComponentStyle: {
        color: Colors.textColor,
        textAlign: "center",
        marginTop: 10,
    },
    animalCodeTextInput: { width: "100%", textAlign: "left", fontSize: 14 },
    imageContainer: {
        borderColor: "#ccc",
        borderWidth: 1,
        padding: 3,
        backgroundColor: "#fff",
        borderRadius: 3,
    },
    inputContainer: {
        padding: "1%",
    },
	headerTitle: {
		fontSize: 20,
		fontWeight: "700",
		color: "grey",
	},
	formContainer: {
		width: "100%",
		height: "100%",
		paddingHorizontal: 20,
		paddingVertical: 20,
		backgroundColor: "white",
	},
	formViews: {
		width: "100%",
		// height: "80%",
		paddingHorizontal: 20,
		paddingVertical: 10,
		backgroundColor: "white",
	},
	Label: {
		marginTop: 20,
		fontSize: 5,
		fontWeight: "200",
	},
	inputFlieds: {
		// borderBottomWidth: 1,
		// borderColor: "grey",
		fontSize: 12,
		color: "black",
		borderColor: "#00008B",
	},
	feetBox: {
		padding: "1%",
		left: "55%",
		bottom: "10.5%",
		width: "45%",
	},
	container: {
		flex: 1,
		alignItems: "center",
		marginTop: 15,
	},
	body: {
		// flex: 1,
		width: "100%",
		height: "100%",
		paddingHorizontal: 10,
		paddingVertical: 20,
		backgroundColor: "white",

	},

	TextInputContainer: {
		marginVertical: 20,
	},
	nextBtn: {
		marginVertical: 12,
		backgroundColor: "#7CC0CF",
		width: "40%",
		height: 40,
		justifyContent: "center",
		alignItems: "center",
		marginLeft: "auto",
		marginRight: "auto",
		borderRadius: 10,
	},
	btnText: {
		color: "white",
	},
});
export default styles;
